// Generated by CoffeeScript 1.4.0
(function() {

  define(["jquery", "use!underscore", "use!backbone"], function($, _, Backbone) {
    var Application, Module, previousGet;
    Module = (function() {

      Module.prototype.name = null;

      Module.prototype.path = null;

      Module.prototype.app = null;

      Module.prototype.layout = null;

      Module.prototype.routerClass = null;

      function Module(options) {
        if (options == null) {
          options = {};
        }
        _.extend(this, {
          Views: {},
          Models: {},
          Collections: {}
        }, options);
      }

      Module.prototype.init = function() {};

      Module.prototype.routes = function(routeParams) {
        return this.routerClass = this.app.Backbone.Router.extend(routeParams);
      };

      Module.prototype._eventHandlers = {};

      Module.prototype.on = function(name, callback) {
        var _base, _ref;
        if (!_.isFunction(callback)) {
          return;
        }
        if ((_ref = (_base = this._eventHandlers)[name]) == null) {
          _base[name] = {};
        }
        this._eventHandlers[name][callback] = callback;
        return this;
      };

      Module.prototype.trigger = function(name, options) {
        var callback, key, _ref;
        if (this._eventHandlers[name]) {
          _ref = this._eventHandlers[name];
          for (key in _ref) {
            callback = _ref[key];
            callback(options);
          }
        }
        return this;
      };

      return Module;

    })();
    previousGet = Backbone.Model.prototype.get;
    Backbone.Model.prototype.get = function(attr) {
      if (typeof this[attr] === 'function') {
        return this[attr]();
      }
      return previousGet.call(this, attr);
    };
    Backbone.Collection.prototype.lazyFetch = function(callback) {
      if (this.models.length) {
        if (callback) {
          callback(this);
        }
      } else {
        this.fetch({
          success: callback,
          silent: true
        });
      }
      return this;
    };
    Application = (function() {

      Application.prototype.layoutClass = null;

      Application.prototype.templaterClass = null;

      Application.prototype.Backbone = Backbone;

      Application.prototype._templater = null;

      Application.prototype._modules = null;

      Application.prototype._configs = null;

      Application.prototype._currentModule = null;

      Application.prototype._ecometConnection = null;

      Application.prototype._ecometSubscriptions = {};

      function Application(options) {
        if (options == null) {
          options = {};
        }
        this._configs = {};
        this._modules = {};
        _.extend(this, options);
      }

      Application.prototype.template = function(tmplPath, context, callback) {
        var _ref;
        if ((_ref = this._templater) == null) {
          this._templater = new this.templaterClass(this);
        }
        return this._templater.render(tmplPath, context, callback);
      };

      Application.prototype.collection = function(collectionClass, params) {
        var _base, _name, _ref, _ref1;
        if ((_ref = collectionClass.__instance) == null) {
          collectionClass.__instance = {};
        }
        return (_ref1 = (_base = collectionClass.__instance)[_name = params ? JSON.stringify(params) : 1]) != null ? _ref1 : _base[_name] = new collectionClass(params);
      };

      Application.prototype.view = function(viewClass, options) {
        var _ref;
        if (viewClass.__instance) {
          viewClass.__instance._configure(options);
          viewClass.__instance._ensureElement();
          viewClass.__instance.delegateEvents();
        } else {
          if ((_ref = viewClass.__instance) == null) {
            viewClass.__instance = new viewClass(options);
          }
        }
        return viewClass.__instance;
      };

      Application.prototype.currentModule = function(module) {
        if (module) {
          this._currentModule = module;
        }
        return this._currentModule;
      };

      Application.prototype.config = function(config) {
        if (typeof config === 'string') {
          return this._configs[config];
        }
        if (_.isObject(config)) {
          return _.extend(this._configs, config);
        }
      };

      Application.prototype.ecometSingle = function(name, callback) {
        var callSubs,
          _this = this;
        callSubs = function(ecomet) {
          if (!(_this._ecometSubscriptions[name] != null)) {
            _this._ecometSubscriptions[name] = true;
            return callback(ecomet);
          }
        };
        if (!this._ecometConnection) {
          return require(["system/libs/ecomet"], function(Ecomet) {
            if (!_this._ecometConnection) {
              _this._ecometConnection = Ecomet.connect({
                host: _this.config('ecomet.host'),
                authUrl: _this.config('api.url') + (_this.config('ecomet.authUrl') || '/auth/ecomet')
              });
            }
            return callSubs(_this._ecometConnection);
          });
        } else {
          return callSubs(this._ecometConnection);
        }
      };

      Application.prototype.initBaseRouter = function(routerParams) {
        var _app;
        new (this.Backbone.Router.extend(routerParams));
        _app = this;
        return $(document).on("click", "a:not([data-bypass])", function(e) {
          var href, root;
          if (e.ctrlKey || e.metaKey) {
            return;
          }
          if ($(this).attr("href") === "" || $(this).attr("href") === "#") {
            e.preventDefault();
            return false;
          }
          href = $(this).prop("href");
          root = location.protocol + "//" + location.host;
          if (href && href.indexOf(root) === 0) {
            e.preventDefault();
            href = href.slice(root.length);
            href = href.replace(/[/# ]*$/g, '');
            _app.Backbone.history.navigate(href, false);
            return _app.Backbone.history.loadUrl(href);
          }
        });
      };

      Application.prototype.navigate = function(href, options) {
        return this.Backbone.history.navigate(href, options);
      };

      Application.prototype.initModules = function(modules) {
        return require(modules, function() {
          var i, module, _i, _len;
          for (i = _i = 0, _len = arguments.length; _i < _len; i = ++_i) {
            module = arguments[i];
            module.path = modules[i];
            module.init();
            if (module.routerClass) {
              new module.routerClass;
            }
          }
          return this.Backbone.history.start({
            pushState: true
          });
        });
      };

      Application.prototype.module = function(name, extraParams) {
        if (!this._modules[name]) {
          this._modules[name] = new Module({
            name: name,
            app: this
          });
          this._modules[name].layout = new this.layoutClass({
            app: this,
            module: this._modules[name]
          });
        }
        if (extraParams) {
          _.extend(this._modules[name], extraParams);
        }
        return this._modules[name];
      };

      return Application;

    })();
    return Application;
  });

}).call(this);
